[platformio]
src_dir = .
include_dir = Core/Inc

[env:nucleo_l476rg]
platform = ststm32
board = nucleo_l476rg
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
board_build.ldscript = STM32L476RGTX_FLASH_SCV.ld
build_src_filter =
    +<Core/Src/>
    +<USB_DEVICE/App/>
    +<USB_DEVICE/Target/>
build_flags =
    -IUSB_DEVICE/App
    -IUSB_DEVICE/Target
