import type { TelemetryRow } from "@/types/telemetry"
import { fmt } from "@/lib/format"

export type TelemetryColumn = { key: keyof TelemetryRow | string; label: string; decimals?: number; suffix?: string }

// V8 wire fields plus ground-side reception and packet-validation metadata.
export const telemetryColumns: TelemetryColumn[] = [
  { key: "pc_receive_time_iso", label: "Ground receive time" },
  { key: "sequence_number", label: "Sequence" },
  { key: "is_duplicate_packet", label: "Duplicate telemetry" },
  { key: "consecutive_duplicate_packets", label: "Consecutive duplicates" },
  { key: "total_duplicate_packets", label: "Total duplicates" },
  { key: "lora_downlink_rssi_dbm", label: "Ground RX RSSI", suffix: " dBm" },
  { key: "lora_downlink_snr_db", label: "Ground RX SNR", suffix: " dB", decimals: 1 },
  { key: "packet_type", label: "Packet type" },
  { key: "protocol_version", label: "Protocol version" },
  { key: "crc_ok", label: "CRC valid" },
  { key: "received_crc16", label: "Packet CRC" },
  { key: "sample_age_ms", label: "Sensor sample age", suffix: " ms" },
  { key: "obc_uptime_ms", label: "TX uptime", suffix: " ms" },
  { key: "scv_mission_elapsed_ms", label: "Mission elapsed", suffix: " ms" },
  { key: "i2c_bus_state_raw", label: "I2C bus state" },
  { key: "gps_valid_raw", label: "GNSS valid" },
  { key: "gnss_utc_sod", label: "GNSS UTC second of day", suffix: " s" },
  { key: "gnss_fix_type", label: "GNSS fix type" },
  { key: "gnss_satellites_used", label: "GNSS satellites" },
  { key: "latitude_deg", label: "GNSS latitude", decimals: 7 },
  { key: "longitude_deg", label: "GNSS longitude", decimals: 7 },
  { key: "gnss_altitude_m", label: "GNSS altitude", suffix: " m", decimals: 1 },
  { key: "vertical_speed_ms", label: "GNSS vertical speed", suffix: " m/s", decimals: 2 },
  { key: "ground_speed_ms", label: "GNSS ground speed", suffix: " m/s", decimals: 2 },
  { key: "course_deg", label: "GNSS course", suffix: " deg", decimals: 2 },
  { key: "imu_valid_raw", label: "IMU valid" },
  { key: "imu_accel_x_g", label: "IMU accel X", suffix: " g", decimals: 3 },
  { key: "imu_accel_y_g", label: "IMU accel Y", suffix: " g", decimals: 3 },
  { key: "imu_accel_z_g", label: "IMU accel Z", suffix: " g", decimals: 3 },
  { key: "imu_gyro_x_dps", label: "IMU gyro X", suffix: " deg/s", decimals: 1 },
  { key: "imu_gyro_y_dps", label: "IMU gyro Y", suffix: " deg/s", decimals: 1 },
  { key: "imu_gyro_z_dps", label: "IMU gyro Z", suffix: " deg/s", decimals: 1 },
  { key: "baro_valid_raw", label: "Barometer valid" },
  { key: "baro_pressure_pa", label: "Barometer pressure", suffix: " Pa" },
  { key: "baro_altitude_m", label: "Barometer altitude", suffix: " m", decimals: 1 },
  { key: "baro_temperature_c", label: "Barometer temperature", suffix: " °C", decimals: 2 },
  { key: "batt_valid_raw", label: "Battery valid" },
  { key: "battery_mv", label: "Battery voltage", suffix: " mV" },
  { key: "coral_valid_raw", label: "Coral valid" },
  { key: "coral_sequence_low", label: "Coral sequence (low 16 bits)" },
  { key: "coral_fraction_percent", label: "Coral cloud fraction", suffix: " %", decimals: 2 },
  { key: "coral_status", label: "Coral status" },
  { key: "coral_result_age_s", label: "Coral result age", suffix: " s" },
  { key: "boot_count", label: "Boot count (saturated)" },
  { key: "flight_state_name", label: "Flight phase" },
  { key: "reset_reason_name", label: "Reset reason" },
  { key: "scv_equipment_enabled", label: "Equipment enabled" },
  { key: "scv_equipment_faults", label: "Equipment faults" },
  { key: "scv_sd_fault_count", label: "SD faults" },
  { key: "scv_watchdog_reset_count", label: "Watchdog resets" },
  { key: "uplink_last_command_id", label: "Last flight command ID" },
  { key: "uplink_last_status_name", label: "Last flight command status" },
  { key: "uplink_last_ack_status_name", label: "Last telemetry ACK status" },
  { key: "lora_last_event_name", label: "Spacecraft LoRa last event" },
  { key: "lora_consecutive_failures", label: "Spacecraft LoRa consecutive failures" },
  { key: "lora_tx_fault_count", label: "Spacecraft LoRa lifetime TX failures" },
  { key: "lora_recovery_count", label: "Spacecraft LoRa recoveries" },
  { key: "lora_rx_mode_active", label: "Spacecraft RX mode active" },
  { key: "lora_last_rx_status_name", label: "Spacecraft RX status" },
  { key: "lora_ack_timeout_count", label: "Telemetry ACK timeouts" },
]

export function formatTelemetryCell(row: TelemetryRow, column: TelemetryColumn) {
  return fmt(row[column.key], column.suffix ?? "", column.decimals)
}
